version: '3.8'

services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://api:8000
    volumes:
      - ./crypto-exchange-frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    restart: always

  api:
    build: ./crypto_exchange_comparison
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crypto_exchange
      - REDIS_URL=redis://redis:6379/0
      - DISABLE_CACHE=true
    depends_on:
      - db
      - redis
    volumes:
      - ./crypto_exchange_comparison:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crypto_exchange
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 